name: Nix CI
on: [push, pull_request]
jobs:
  ci-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Nix with flakes enabled
        uses: cachix/install-nix-action@v16
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes
      - name: Check Nix code formatting
        run: nix fmt -- --ci
  