name: std CI/CD

on: [push, pull_request]

permissions:
  id-token: write
  contents: read

concurrency:
  group: std-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  discover:
    outputs:
      hits: ${{ steps.discovery.outputs.hits }}
    runs-on: ubuntu-latest
    steps:
      - uses: nixbuild/nix-quick-install-action@master
      - uses: nixbuild/nixbuild-action@v17
        with:
          nixbuild_ssh_key: ${{ secrets.SSH_PRIVATE_KEY }}
          generate_summary_for: job
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - uses: divnix/std-action/discover@main
        id: discovery

  build: &job
    needs: discover
    name: ${{ matrix.target.jobName }}
    runs-on: ubuntu-latest
    if: fromJSON(needs.discover.outputs.hits).packages.build != '{}'
    strategy:
      matrix:
        target: ${{ fromJSON(needs.discover.outputs.hits).packages.build }}
    steps:
      - uses: nixbuild/nix-quick-install-action@master
      - uses: nixbuild/nixbuild-action@v17
        with:
          nixbuild_ssh_key: ${{ secrets.SSH_PRIVATE_KEY }}
          generate_summary_for: job
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - uses: divnix/std-action/run@main

  images:
    <<: *job
    needs: [discover, build]
    if: fromJSON(needs.discover.outputs.hits).oci-images.publish != '{}'
    strategy:
      matrix:
        target: ${{ fromJSON(needs.discover.outputs.hits).oci-images.publish }}

  # deploy:
  #   <<: *job
  #   needs: [discover, images]
  #   environment:
  #     name: development
  #     url: https://my.dev.example.com
  #   if: fromJSON(needs.discover.outputs.hits).deployments.apply != '{}'
  #   strategy:
  #     matrix:
  #       target: ${{ fromJSON(needs.discover.outputs.hits).deployments.apply }}

  darwin-rollout:
    <<: *job
    needs: [discover, images]
    runs-on: macos-latest
    if: fromJSON(needs.discover.outputs.hits).darwinConfigurations.switch != '{}'
    strategy:
      matrix:
        target: ${{ fromJSON(needs.discover.outputs.hits).darwinConfigurations.switch }}
